# Investigating Economical Indicators for Recession

# 1. Recession Indicators

# Part A: Examining OECD CCI

In [281]:
import numpy as np
import pandas as pd

#X feature data: Standardized confidence economic indicators showing economic growth or decay
econ_data=pd.read_csv('CLI_Data.csv')
#Y label data: Recession data for US
rec_data=pd.read_csv('USREC.csv')

#Find and store data for United States
filter_us = econ_data.Country.str.contains("United States")
#Extract CCI values from the data
filter_cci = econ_data.SUBJECT.str.contains("CSCICP03")

us_data = econ_data[filter_us]
cci_data = us_data[filter_cci]

#Use 75% of data for training; 25% for testing
training_size = 0.75

X_cci = cci_data.loc[:, 'Value'].values
Y = rec_data.iloc[:, :2].values

#Remove data before 1970 so X and Y match
index = 0
for val in Y:
    year = val[0].split("-")[0]
    if year == '1970':
        break
    index += 1
Y = Y[index:]

#Remove dates from Y data
Y = Y[:,1:]
Y = Y.reshape(Y.shape[0])
Y = Y.astype('int')
X = X_cci.reshape(-1, 1)

x_train = X[:int(len(X)*training_size)]
y_train = Y[:int(len(Y)*training_size)]
x_test = X[int(len(X)*training_size):]
y_test = Y[int(len(Y)*training_size):]

#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  from ipykernel import kernelapp as app


Apply Logistic Regression to data

In [282]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(solver="liblinear")

logreg.fit(x_train, y_train)

y_predict = logreg.predict(x_test)

print("Logistic Regression classification accuracy: " + str(accuracy_score(y_test, y_predict)))
confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Logistic Regression classification accuracy: 0.92
[[122  10]
 [  2  16]]


Use Support Vector Machines on data

In [283]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale', kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Support Vector Machine classification accuracy: 0.94
[[126   6]
 [  3  15]]


# Part B: Unemployment Rate

In [284]:
#X feature data: Unemployment rates from Jan 1970 to Nov 2019
unemp_data=pd.read_csv('OECD_Unemployment_Rate.csv')
#Y label data: Recession indicators for Canada
canrec_data=pd.read_csv('CANREC.csv')

#Find and store data for United States and Canada
filterunemp_us = unemp_data.LOCATION.str.contains("USA")
filterunemp_can = unemp_data.LOCATION.str.contains("CAN")

unempus_data = unemp_data[filterunemp_us]
unempcan_data = unemp_data[filterunemp_can]

#Extracting and storing unemploying rate values for US and Canada
X_usunemp = unempus_data.loc[:, 'Value'].values
X_can = unempcan_data.loc[:, 'Value'].values

#Remove Last entry from canada unemployment data so data sets match
X_can = X_can[:-1]

X_us = X_usunemp.reshape(-1, 1)
X_can = X_can.reshape(-1, 1)

#Use 75% of data for training; 25% for testing
training_size = 0.75

x_train = X_us[:int(len(X_us)*training_size)]
x_test = X_us[int(len(X_us)*training_size):]
y_train = Y[:int(len(Y)*training_size)]
y_test = Y[int(len(Y)*training_size):]

#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

Apply Logistic Regression to data

In [285]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(solver="liblinear")

logreg.fit(x_train, y_train)

y_predict = logreg.predict(x_test)

print("Logistic Regression classification accuracy: " + str(accuracy_score(y_test, y_predict)))
confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Logistic Regression classification accuracy: 0.88
[[132   0]
 [ 18   0]]


Apply Support Vector Machine to data

In [286]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale',  kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Support Vector Machine classification accuracy: 0.88
[[132   0]
 [ 18   0]]


Make Predictions on Canada Recession Data

In [287]:
Y_can = canrec_data.iloc[:, :2].values

#Remove data before 1970 so X and Y match
index = 0
for val in Y_can:
    year = val[0].split("-")[0]
    if year == '1970':
        break
    index += 1
Y_can = Y_can[index:]

#Remove dates from Y data
Y_can = Y_can[:,1:]
Y_can = Y_can.reshape(Y_can.shape[0])
Y_can = Y_can.astype('int')

#Use 75% of data for training; 25% for testing
training_size = 0.75

x_train = X_can[:int(len(X_can)*training_size)]
y_train = Y_can[:int(len(Y_can)*training_size)]
x_test = X_can[int(len(X_can)*training_size):]
y_test = Y_can[int(len(Y_can)*training_size):]

#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

#Apply Logistic Regression to Canada Unemployment data

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(solver="liblinear")

logreg.fit(x_train, y_train)

y_predict = logreg.predict(x_test)

print("Logistic Regression classification accuracy: " + str(accuracy_score(y_test, y_predict)))
confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

#Apply SVM to Canada Unemployment data

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale', kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Logistic Regression classification accuracy: 0.5066666666666667
[[76  0]
 [74  0]]
Support Vector Machine classification accuracy: 0.5066666666666667
[[76  0]
 [74  0]]


# Part C:  Interest Rate Spread

In [288]:
#X feature data: US 10-Year Treasury Constant Maturity Minus Federal Funds Rate
yield_data=pd.read_csv('Ten_Year_Treasury_Maturity.csv')

X_yield = yield_data.loc[:, 'T10YFF'].values
X = X_yield.reshape(-1, 1)

#Use 75% of data for training; 25% for testing
training_size = 0.75
x_train = X[:int(len(X)*training_size)]
y_train = Y[:int(len(Y)*training_size)]
x_test = X[int(len(X)*training_size):]
y_test = Y[int(len(Y)*training_size):]

#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

Apply Logistic Regression to Yield Curve Data

In [289]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(solver="liblinear")

logreg.fit(x_train, y_train)

y_predict = logreg.predict(x_test)

print("Logistic Regression classification accuracy: " + str(accuracy_score(y_test, y_predict)))
confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Logistic Regression classification accuracy: 0.88
[[132   0]
 [ 18   0]]


Apply Support Vector Machine to Yield Curve Data

In [290]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale', kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Support Vector Machine classification accuracy: 0.88
[[132   0]
 [ 18   0]]


# Part D: Examining OECD BCI

In [291]:
filter_bci = econ_data.SUBJECT.str.contains("BSCICP03")
bci_data = us_data[filter_bci]

X_bci = bci_data.loc[:, 'Value'].values
X = X_bci.reshape(-1, 1)

#Use 75% of data for training; 25% for testing
training_size = 0.75
x_train = X[:int(len(X)*training_size)]
y_train = Y[:int(len(Y)*training_size)]
x_test = X[int(len(X)*training_size):]
y_test = Y[int(len(Y)*training_size):]

#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

[0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0]


C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


Apply Logistic Regression to BCI data

In [292]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

logreg = LogisticRegression(solver="liblinear")

logreg.fit(x_train, y_train)

y_predict = logreg.predict(x_test)

print("Logistic Regression classification accuracy: " + str(accuracy_score(y_test, y_predict)))
confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Logistic Regression classification accuracy: 0.9333333333333333
[[132   0]
 [ 10   8]]


Apply Support Vector Machine to BCI data

In [293]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale', kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Support Vector Machine classification accuracy: 0.9333333333333333
[[132   0]
 [ 10   8]]


# 2. Making a Predictive Model with all Indicators

In [294]:
#Want to store all indicator data investigated so far into set of training data
X_cci = X_cci.reshape(X_cci.shape[0])
X_usunemp = X_usunemp.reshape(X_usunemp.shape[0])
X_yield = X_yield.reshape(X_yield.shape[0])
X_bci = X_bci.reshape(X_bci.shape[0])

feature_data = [X_cci, X_usunemp,  X_yield, X_bci]

feature_data = np.stack(feature_data, axis=1)

#Use 75% of data for training; 25% for testing
training_size = 0.75
x_train = feature_data[:int(len(feature_data)*training_size)]
y_train = Y[:int(len(Y)*training_size)]
x_test = feature_data[int(len(feature_data)*training_size):]
y_test = Y[int(len(Y)*training_size):]

Apply Support Vector Machine to Indicator Data

In [295]:
#Scale data
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(x_train)
x_train = sc.transform(x_train)
x_test = sc.transform(x_test)

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

svm = SVC(gamma='scale', kernel='linear')

svm.fit(x_train, y_train)

y_predict = svm.predict(x_test)

print("Support Vector Machine classification accuracy: " + str(accuracy_score(y_test, y_predict)))

confmatrix = confusion_matrix(y_test, y_predict)
print(confmatrix)

Support Vector Machine classification accuracy: 0.9733333333333334
[[130   2]
 [  2  16]]
